name: 🚀 Production Pipeline

on:
  push:
    branches: [main, production]

# ====================================================
# VARS (di Gitea → Repository → Settings → Variables)
# ====================================================
# - WA_ENDPOINT
# - PROD_WA_TARGET
# - IMAGE_NAME
# - PROD_DEPLOY_URL
# - PROD_DEPLOY_PORT
# - NEXT_PUBLIC_API_BASE_URL
# - NEXT_PUBLIC_MAINTENANCE_MODE
# - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
# - RECAPTCHA_SECRET_KEY
# ====================================================

# ====================================================
# SECRETS (di Gitea → Repository → Settings → Secrets)
# ====================================================
# - REGISTRY_URL
# - REGISTRY_USERNAME
# - REGISTRY_PASSWORD
# - PROD_HOSTNAME
# - PROD_USERNAME 
# - PROD_PASSWORD
# ====================================================

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ==================================================
      # 🔔 Notify Build START with commit info
      # ==================================================
      - name: 🔔 WA Notify - Build Started
        run: |
          MSG=$(jq -n --arg branch "$GITHUB_REF_NAME" \
            --arg target "${{ vars.PROD_WA_TARGET }}" \
            --arg actor "$GITHUB_ACTOR" \
            --arg msg "$(jq -r '.head_commit.message' $GITHUB_EVENT_PATH)" \
            --arg repo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --arg deploy "${{ vars.PROD_DEPLOY_URL }}:${{ vars.PROD_DEPLOY_PORT }}" \
            '{ target: $target, message: "🚀 Build Started (Production)\n\n- Branch: \($branch)\n- Commit by: \($actor)\n- Repo URL: \($repo)\n- Deploy URL: \($deploy)\n- Message: \($msg)"}')

          curl -X POST "${{ vars.WA_ENDPOINT }}" \
             -H "Content-Type: application/json" \
             -d "$MSG"

      # ==================================================
      # 😮‍💨 Docker Login
      # ==================================================
      - name: 😮‍💨 Login to Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ secrets.REGISTRY_URL }}" \
            -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      # ==================================================
      # 🔥 Build & Push Docker Image
      # ==================================================
      - name: 🔥 Build Docker Image
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }} \
          --build-arg NEXT_PUBLIC_MAINTENANCE_MODE=${{ vars.NEXT_PUBLIC_MAINTENANCE_MODE }} \
          --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ vars.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }} \
          --build-arg RECAPTCHA_SECRET_KEY=${{ vars.RECAPTCHA_SECRET_KEY }} \
          -t ${{ secrets.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:prod-latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:prod-latest

      # ==================================================
      # 🔔 WA Notify - Build Success
      # ==================================================
      - name: 🔔 WA Notify - Build Success
        if: success()
        run: |
          MSG=$(jq -n --arg branch "$GITHUB_REF_NAME" \
            --arg target "${{ vars.PROD_WA_TARGET }}" \
            --arg actor "$GITHUB_ACTOR" \
            --arg msg "$(jq -r '.head_commit.message' $GITHUB_EVENT_PATH)" \
            --arg sha "$GITHUB_SHA" \
            --arg repo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --arg deploy "${{ vars.PROD_DEPLOY_URL }}:${{ vars.PROD_DEPLOY_PORT }}" \
            '{ target: $target, message: "✅ Build Success (Production)\n\n- Branch: \($branch)\n- Commit by: \($actor)\n- Repo URL: \($repo)\n- Deploy URL: \($deploy)\n- Message: \($msg)"}')

          curl -X POST "${{ vars.WA_ENDPOINT }}" \
                -H "Content-Type: application/json" \
                -d "$MSG"

      # ==================================================
      # 🔔 WA Notify - Build Failed
      # ==================================================
      - name: 🔔 WA Notify - Build Failed
        if: failure()
        run: |
          MSG=$(jq -n --arg branch "$GITHUB_REF_NAME" \
            --arg target "${{ vars.PROD_WA_TARGET }}" \
            --arg actor "$GITHUB_ACTOR" \
            --arg msg "$(jq -r '.head_commit.message' $GITHUB_EVENT_PATH)" \
            --arg repo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --arg deploy "${{ vars.PROD_DEPLOY_URL }}:${{ vars.PROD_DEPLOY_PORT }}" \
            '{ target: $target, message: "❌ Build Failed (Production)\n\n- Branch: \($branch)\n- Commit by: \($actor)\n- Repo URL: \($repo)\n- Deploy URL: \($deploy)\n- Message: \($msg)"}')

          curl -X POST "${{ vars.WA_ENDPOINT }}" \
                -H "Content-Type: application/json" \
                -d "$MSG"

      # ==================================================
      # 🆙 DEPLOY TO SERVER
      # ==================================================
      - name: 🆙 Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PROD_HOSTNAME }}
          port: ${{ secrets.PROD_PORT }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
            docker pull ${{ secrets.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:prod-latest

            if [ $(docker ps -a -q -f name=${{ vars.IMAGE_NAME }}-dev --restart=always ) ]; then
              echo "Stopping existing container..."
              docker stop ${{ vars.IMAGE_NAME }}-prod || true
              echo "Removing existing container..."
              docker rm -f ${{ vars.IMAGE_NAME }}-prod || true
            fi
            
            docker run -d --name ${{ vars.IMAGE_NAME }}-prod -p ${{ vars.PROD_DEPLOY_PORT }}:3000 \
            -e NEXT_PUBLIC_API_BASE_URL="${{ vars.NEXT_PUBLIC_API_BASE_URL }}" \
            -e NEXT_PUBLIC_MAINTENANCE_MODE="${{ vars.NEXT_PUBLIC_MAINTENANCE_MODE }}" \
            -e NEXT_PUBLIC_RECAPTCHA_SITE_KEY="${{ vars.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" \
            -e RECAPTCHA_SECRET_KEY="${{ vars.RECAPTCHA_SECRET_KEY }}" \
            ${{ secrets.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:prod-latest

      # ==================================================
      # 🔔 WA Notify - Deploy Success
      # ==================================================
      - name: 🔔 WA Notify - Deploy Success
        if: success()
        run: |
          MSG=$(jq -n --arg branch "$GITHUB_REF_NAME" \
            --arg target "${{ vars.PROD_WA_TARGET }}" \
            --arg actor "$GITHUB_ACTOR" \
            --arg sha "$GITHUB_SHA" \
            --arg repo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --arg deploy "${{ vars.PROD_DEPLOY_URL }}:${{ vars.PROD_DEPLOY_PORT }}" \
            '{ target: $target, message: "✅ Deploy Success (Production)\n\n- Branch: \($branch)\n- Commit by: \($actor)\n- Repo URL: \($repo)\n- Deploy URL: \($deploy)"}')

          curl -X POST "${{ vars.WA_ENDPOINT }}" \
            -H "Content-Type: application/json" \
            -d "$MSG"

      # ==================================================
      # 🔔 DEPLOY FAILED
      # ==================================================
      - name: 🔔 WA Notify - Deploy Failed
        if: failure()
        run: |
          MSG=$(jq -n --arg branch "$GITHUB_REF_NAME" \
            --arg target "${{ vars.PROD_WA_TARGET }}" \
            --arg actor "$GITHUB_ACTOR" \
            --arg repo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --arg deploy "${{ vars.PROD_DEPLOY_URL }}:${{ vars.PROD_DEPLOY_PORT }}" \
            '{ target: $target, message: "❌ Deploy Failed (Production)\n\n- Branch: \($branch)\n- Commit by: \($actor)\n- Repo URL: \($repo)\n- Deploy URL: \($deploy)"}')

          curl -X POST "${{ vars.WA_ENDPOINT }}" \
            -H "Content-Type: application/json" \
            -d "$MSG"
